steps:

# Step 1: Install Maven dependencies
- name: maven
  entrypoint: mvn
  args: ["install"]

# Step 2: Deploy Configurations
- name: maven
  entrypoint: mvn
  args:
    - install
    - "-Ptest"
    - "-Dorg=$_ORG"
    - "-Denv=$_ENV"
    - "-Dapigee.config.options=update"
  # dir: "apigee/config"


substitutions:
  _ORG: "tw-rd-ca-paggie-chen-394703"
  _ENV: "eval"

logsBucket: "gs://paggie-test-bucket"

timeout: "1200s"
