steps:

  # Step 1: Clone the repository
  - name: "gcr.io/cloud-builders/git"
    id: clone-repo
    entrypoint: "git"
    args: ["clone", "https://github.com/PaggieChen/apigee-cicd-demo.git"]

  # Step 2: Build the project using Maven
  - name: maven
    id: build-project
    dir: "apigee-cicd-demo/Mock-v1" # Ensure we are in the correct directory
    entrypoint: "mvn"
    args: ["clean", "install"]

  # Step 3: Deploy Configurations
  - name: maven
    id: deploy
    dir: "apigee-cicd-demo/Mock-v1" # Ensure we are in the correct directory
    entrypoint: "mvn"
    args:
      - install
      - "-Ptest"
      - "-Dorg=$_ORG"
      - "-Denv=$_ENV"
      - "-Dapigee.config.options=update"

substitutions:
  _ORG: "tw-rd-ca-paggie-chen-394703"
  _ENV: "eval"

logsBucket: "gs://paggie-test-bucket"

timeout: "1200s"
