steps:
  # Step 1: Clone the repository
  - name: "gcr.io/cloud-builders/git"
    id: clone-repo
    entrypoint: "git"
    args: ["clone", "https://github.com/PaggieChen/apigee-cicd-demo.git"]


  - name: 'bash'
    script: |
      #!/usr/bin/env bash
      printf "%s" "$$SA" > /workspace/sa-key.json
      cat /workspace/sa-key.json
    secretEnv: ['SA']


  # Step 2: Deploy Configurations using Maven
  - name: maven
    id: deploy
    dir: "apigee-cicd-demo/Mock-v1"  # Ensure we are in the correct directory
    entrypoint: "bash"
    args: ['-c', 'mvn install -Ptest -Dorg=tw-rd-ca-paggie-chen-394703 -Denv=eval -Dapigee.config.options=update -Dfile=/workspace/sa-key.json']
    secretEnv: ['SA']

availableSecrets:
  secretManager:
  - versionName: projects/609801163603/secrets/apigee-secret/versions/1
    env: 'SA'

logsBucket: "gs://paggie-test-bucket"

timeout: "1200s"




